select * from SuperPerson;
select * from Sidekick;
select * from Powers;
select * from OriginStory;
select * from Hideout;
select * from Equipment;
select * from Disaster;
select * from HeroDisaster;
select * from VillianDisaster;